#spring.profiles.active=dev 可通过此配置不同的环境变量
server:
  port: 8080
debug: true
logging:
    level:
      root: debug
      com.security.demo.SecurityDemo.mapper: trace
spring:
  freemarker:
    template-loader-path: classpath:/templates/admin
  redis:
    host: 127.0.0.1
    database: 0
  datasource:
      driver_class_namel: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.3.58:3316/test?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username:
      password:

      # 初始化大小，最小，最大
      initial-size: 1
      max-active: 20
      min-idle: 3
      #最大连接等待超时时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validationQuery: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
# mybatis
mybatis:
  type-aliases-package: com.security.demo.SecurityDemo.model
  mapper-locations: classpath:mapperXml/*.xml
# Mapper
mapper:
  mappers: com.security.demo.SecurityDemo.common.BaseMapper
  not-empty: false
  identity: MYSQL
#分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql





